# Generated by Django 3.2.6 on 2021-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_frm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polacy_no', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('fname', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_brth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_no', models.IntegerField(null=True)),
            ],
        ),
    ]
