# Generated by Django 3.2.5 on 2021-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='firemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polacy_no', models.IntegerField(null=True)),
                ('type_property', models.CharField(max_length=40)),
                ('owner_name', models.CharField(max_length=10, null=True)),
                ('vehicle_wheel', models.IntegerField(null=True)),
                ('cause_name', models.CharField(max_length=10, null=True)),
                ('fire_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polacy_no', models.IntegerField(null=True)),
                ('vehicle_no', models.IntegerField(null=True)),
                ('owner_name', models.CharField(max_length=10, null=True)),
                ('vehicle_wheel', models.IntegerField(null=True)),
                ('vehicle_name', models.CharField(max_length=10, null=True)),
                ('vehicle_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_no', models.IntegerField(null=True)),
            ],
        ),
    ]
