# Generated by Django 3.2.6 on 2021-08-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0002_firemodel_vmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vmodel',
        ),
    ]
