# Generated by Django 3.2.6 on 2021-08-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0003_delete_vmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='firemodel',
        ),
    ]
