# Generated by Django 3.2.6 on 2021-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0004_delete_firemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_frm',
            name='polacy',
            field=models.CharField(choices=[('50 K', '50 K'), ('1 Lakhs', '1 Lakhs')], default='50 K', max_length=50),
            preserve_default=False,
        ),
    ]
