# Generated by Django 3.2.6 on 2021-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0005_student_frm_polacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_frm',
            name='polacy',
            field=models.CharField(choices=[('10 K', '10 K'), ('50 K', '50 K'), ('1 Lakhs', '1 Lakhs'), ('life-time', 'life-time')], max_length=50),
        ),
    ]
