# Generated by Django 3.2.6 on 2021-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechileapp', '0002_alter_vmodel_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmodel',
            name='owner_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vmodel',
            name='vehicle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
