# Generated by Django 3.2.6 on 2021-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechileapp', '0003_auto_20210820_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmodel',
            name='polacy',
            field=models.CharField(choices=[('3K', '3K'), ('10K', '10K'), ('25Lakhs', '25Lakhs'), ('life-time', 'life-time')], default='3k', max_length=50),
            preserve_default=False,
        ),
    ]
