# Generated by Django 3.2.6 on 2021-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire_mdl',
            name='polacy',
            field=models.CharField(choices=[('50K', '50K'), ('2.5 Lakh', '2.5 Lakh'), ('10 Lakhs', '10 Lakhs'), ('life-time', 'life-time')], default='50k', max_length=50),
            preserve_default=False,
        ),
    ]
