# Generated by Django 3.2.6 on 2021-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0002_fire_mdl_polacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire_mdl',
            name='cause_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
